"""2  миграция

Revision ID: 04416d3b4623
Revises: 5984f8d6fb08
Create Date: 2024-05-02 00:23:59.302025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04416d3b4623'
down_revision: Union[str, None] = '5984f8d6fb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locktime', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locktime')
    # ### end Alembic commands ###
